// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del runtime: 17.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WooW.SB.Config.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using WooW.Core;
    using WooW.SB.Config;
    using WooW.SB.Config.Enum;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ttModeloServiceInterface : ttModeloServiceInterfaceBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttModeloServiceInterface
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using WooW.Core.Server;
using WooW.Core;
using WooW.Core.Common;
using WooW.DTO;
using WooW.Model;
using ServiceStack;
using ServiceStack.OrmLite;

namespace WooW.ServiceInterface
{
    public class ");
            
            #line 28 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("ServiceInterface : Service\r\n    {\r\n        public IAutoQueryDb AutoQuery { get; s" +
                    "et; }\r\n\r\n#if DEBUG\r\n        public object Get(");
            
            #line 33 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(@"AutoQuery query)
        {
            var wotarget = new WoTargetConnection(Request, Db);
            var queryResult = AutoQuery.CreateQuery(query, Request, wotarget.Db);
            return AutoQuery.Execute(query, queryResult, wotarget.Db);
        }
#endif


");
            
            #line 42 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
      if (modelo.TipoModelo != WoTypeModel.Parameter) 
        {
            
            #line default
            #line hidden
            this.Write("        public WoODataResponse<dynamic> Get(");
            
            #line 44 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("List ODataRequest)\r\n        {\r\n            return WoGenericService.ODataGet<");
            
            #line 46 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(new WoTargetConnection(Request, Db), Request, ODataRequest, true);\r\n        }\r\n" +
                    "");
            
            #line 48 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
      }
            
            #line default
            #line hidden
            this.Write("\r\n        public ");
            
            #line 50 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Get(");
            
            #line 50 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Get GetRequest)\r\n        {\r\n");
            
            #line 52 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
      if (modelo.TipoModelo != WoTypeModel.Parameter) 
        {
            
            #line default
            #line hidden
            this.Write("            return ");
            
            #line 54 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(".Get(new WoTargetConnection(Request, Db), GetRequest, WoGetFlags.FillLookUpDescri" +
                    "ption | WoGetFlags.ApplyFilter);\r\n");
            
            #line 55 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
      }
        else 
        {
            
            #line default
            #line hidden
            this.Write("            return ");
            
            #line 58 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(".Get(new WoTargetConnection(Request, Db), WoGetFlags.FillLookUpDescription | WoGe" +
                    "tFlags.ApplyFilter);\r\n");
            
            #line 59 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
      }
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public ");
            
            #line 62 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Get(");
            
            #line 62 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Single SingleRequest)\r\n        {\r\n");
            
            #line 64 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
      if (modelo.TipoModelo != WoTypeModel.Parameter) 
        {
            
            #line default
            #line hidden
            this.Write("            return ");
            
            #line 66 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(".Single(new WoTargetConnection(Request, Db), SingleRequest, WoGetFlags.FillLookUp" +
                    "Description | WoGetFlags.ApplyFilter);\r\n");
            
            #line 67 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
      }
        else 
        {
            
            #line default
            #line hidden
            this.Write("            return ");
            
            #line 70 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(".Single(new WoTargetConnection(Request, Db), WoGetFlags.FillLookUpDescription | W" +
                    "oGetFlags.ApplyFilter);\r\n");
            
            #line 71 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
      }
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n\r\n\r\n");
            
            #line 76 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
      if ((modelo.TipoModelo != WoTypeModel.Control)
            && (modelo.TipoModelo != WoTypeModel.Kardex)
            && (modelo.TipoModelo != WoTypeModel.DataMart) ) 
        {

            foreach(Transicion tra in modelo.Diagrama.Transiciones.Where( e => e.EstadoInicial == 0 && ((e.Tipo == eTransicionTipo.Local ) || (e.Tipo == eTransicionTipo.Publica ))  ) )
            {
            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 83 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Post(");
            
            #line 83 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 83 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" dtoRequest)\r\n        {\r\n            return ");
            
            #line 85 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(".Post(new WoTargetConnection(Request, Db), dtoRequest);\r\n        }\r\n\r\n        pub" +
                    "lic ");
            
            #line 88 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("[] Post(");
            
            #line 88 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 88 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write("[] dtoRequests)\r\n        {\r\n            var list = new List<");
            
            #line 90 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(@">();
            var woTarget = new WoTargetConnection(Request, Db);

            using (var dbTrans = woTarget.Db.OpenTransaction())
            {
                try
                {
                    foreach (var dtoRequest in dtoRequests)
                        list.Add(");
            
            #line 98 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(@".Post(woTarget, dtoRequest));

                    dbTrans.Commit();
                }

                catch (Exception ex)
                {
                    dbTrans.Rollback();
                    throw ex;
                }
            }
            return list.ToArray();
        }

");
            
            #line 112 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
          }

            foreach(Transicion tra in modelo.Diagrama.Transiciones.Where( e => e.EstadoInicial != 0 && ((e.Tipo == eTransicionTipo.Local ) || (e.Tipo == eTransicionTipo.Publica ))  ) )
            {
                Estado estado = modelo.Diagrama.Estados.Where( es => es.NumId == tra.EstadoFinal ).FirstOrDefault();

                if(estado == null)
                    throw new Exception($"No se encontró el estado {tra.EstadoFinal} para el modelo {modelo.Id} transición {tra.Id}");

                if(estado.Tipo == eEstadoTipo.FinalAlternativo) 
                {
            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 123 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Put(");
            
            #line 123 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 123 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" dtoRequest)\r\n        {\r\n            return ");
            
            #line 125 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(".SoftDelete(new WoTargetConnection(Request, Db), dtoRequest);\r\n        }\r\n\r\n     " +
                    "   public ");
            
            #line 128 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("[] Post(");
            
            #line 128 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 128 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write("[] dtoRequests)\r\n        {\r\n            var list = new List<");
            
            #line 130 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(@">();
            var woTarget = new WoTargetConnection(Request, Db);

            using (var dbTrans = woTarget.Db.OpenTransaction())
            {
                try
                {
                    foreach (var dtoRequest in dtoRequests)
                        list.Add(");
            
            #line 138 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(@".SoftDelete(woTarget, dtoRequest));

                    dbTrans.Commit();
                }

                catch (Exception ex)
                {
                    dbTrans.Rollback();
                    throw ex;
                }
            }
            return list.ToArray();
        }

        ");
            
            #line 152 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
      }
                else
                { 
            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 155 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Patch(");
            
            #line 155 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 155 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" dtoRequest)\r\n        {\r\n            return ");
            
            #line 157 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(".Patch(new WoTargetConnection(Request, Db), dtoRequest);\r\n        }\r\n\r\n        pu" +
                    "blic ");
            
            #line 160 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Put(");
            
            #line 160 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 160 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" dtoRequest)\r\n        {\r\n            return ");
            
            #line 162 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(".Put(new WoTargetConnection(Request, Db), dtoRequest);\r\n        }\r\n\r\n        publ" +
                    "ic ");
            
            #line 165 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("[] Post(");
            
            #line 165 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 165 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write("[] dtoRequests)\r\n        {\r\n            var list = new List<");
            
            #line 167 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(@">();
            var woTarget = new WoTargetConnection(Request, Db);

            using (var dbTrans = woTarget.Db.OpenTransaction())
            {
                try
                {
                    foreach (var dtoRequest in dtoRequests)
                        list.Add(");
            
            #line 175 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(@".Put(woTarget, dtoRequest));

                    dbTrans.Commit();
                }

                catch (Exception ex)
                {
                    dbTrans.Rollback();
                    throw ex;
                }
            }
            return list.ToArray();
        }

");
            
            #line 189 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
              }
            }
           if(modelo.bPostCondicionesExist) {
                foreach(Transicion tra in modelo.Diagrama.Transiciones.Where( e => ((modelo.TipoModelo == WoTypeModel.TransactionContable) && (e.EstadoFinal == 300)) && ((e.Tipo == eTransicionTipo.Local ) || (e.Tipo == eTransicionTipo.Publica )))) // Contabilizado
                {
            
            #line default
            #line hidden
            this.Write("        public WoConPolizaRegistraYAfectar Get(");
            
            #line 194 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("PolizaPrevia PolizaPreviaRequest)\r\n        {\r\n            return ");
            
            #line 196 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(".PolizaPrevia(new WoTargetConnection(Request, Db), PolizaPreviaRequest);\r\n       " +
                    " }\r\n");
            
            #line 198 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
              }
            }
        }
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 203 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
      if ((modelo.TipoModelo == WoTypeModel.CatalogType) ||
            (modelo.TipoModelo == WoTypeModel.Catalog))
        {
            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 206 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Delete(");
            
            #line 206 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Borrar dtoRequest)\r\n        {\r\n            return ");
            
            #line 208 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(".Delete(new WoTargetConnection(Request, Db), dtoRequest);  \r\n        }\r\n\r\n       " +
                    " public ");
            
            #line 211 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("[] Post(");
            
            #line 211 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Borrar[] dtoRequests)\r\n        {\r\n            var list = new List<");
            
            #line 213 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(@">();
            var woTarget = new WoTargetConnection(Request, Db);

            using (var dbTrans = woTarget.Db.OpenTransaction())
            {
                try
                {
                    foreach (var dtoRequest in dtoRequests)
                        list.Add(");
            
            #line 221 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(@".Delete(woTarget, dtoRequest));

                    dbTrans.Commit();
                }

                catch (Exception ex)
                {
                    dbTrans.Rollback();
                    throw ex;
                }
            }
            return list.ToArray();
        }
");
            
            #line 234 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"
      }
            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 237 "C:\Frog\WooW.SB.Config\Templates\ttModeloServiceInterface.tt"

public Modelo modelo { get; set; }  

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class ttModeloServiceInterfaceBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
