// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del runtime: 17.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WooW.SB.Config.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using WooW.Core;
    using WooW.SB.Config;
    using WooW.SB.Config.Enum;
    using WooW.SB.UI.EnumExtension;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ttModeloServicioCliente : ttModeloServicioClienteBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttModeloServicioCliente
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated> 
// ------------------------------------------------------------------------------//
using WooW.Core;
using WooW.Core.Common;
using WooW.DTO; 
using ServiceStack;

namespace WooW.Model
{
    public partial class ");
            
            #line 26 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n\r\n        public static WoODataResponse<");
            
            #line 29 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> List(\r\n            JsonApiClient Client, ");
            
            #line 30 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("List GetRequest)\r\n        {\r\n            return Client.Send<WoODataResponse<");
            
            #line 32 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">>(GetRequest);\r\n        }\r\n\r\n        public static async Task<WoODataResponse<");
            
            #line 35 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">> ListAsync(\r\n            JsonApiClient Client, ");
            
            #line 36 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("List GetRequest)\r\n        {\r\n            return await Client.SendAsync<WoODataRes" +
                    "ponse<");
            
            #line 38 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">>(GetRequest);\r\n        }\r\n\r\n        public static ");
            
            #line 41 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Get(\r\n            JsonApiClient Client, ");
            
            #line 42 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Get GetRequest)\r\n        {\r\n            return Client.Send<");
            
            #line 44 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(GetRequest);\r\n        }\r\n\r\n        public static async Task<");
            
            #line 47 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> GetAsync(\r\n            JsonApiClient Client, ");
            
            #line 48 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Get GetRequest)\r\n        {\r\n            return await Client.SendAsync<");
            
            #line 50 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(GetRequest);\r\n        }\r\n\r\n        public static ");
            
            #line 53 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Get(\r\n            JsonApiClient Client, ");
            
            #line 54 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TipoId));
            
            #line default
            #line hidden
            this.Write(" Id)\r\n        {\r\n            return Client.Send<");
            
            #line 56 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(\r\n                new ");
            
            #line 57 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Get()\r\n                {\r\n                    Id = Id\r\n                });\r\n     " +
                    "   }\r\n\r\n\r\n        public static ");
            
            #line 64 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" GetCheck(\r\n            JsonApiClient Client, ");
            
            #line 65 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TipoId));
            
            #line default
            #line hidden
            this.Write(" Id)\r\n        {\r\n            var o");
            
            #line 67 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" = Client.Send<");
            
            #line 67 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(\r\n                new ");
            
            #line 68 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Get()\r\n                {\r\n                    Id = Id\r\n                });\r\n\r\n   " +
                    "         WoGetExcepcion.CheckIfNullThenExcept(o");
            
            #line 73 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(", Id);\r\n\r\n            return o");
            
            #line 75 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n\r\n        public static async Task<");
            
            #line 78 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> GetAsync(\r\n            JsonApiClient Client, ");
            
            #line 79 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TipoId));
            
            #line default
            #line hidden
            this.Write(" Id)\r\n        {\r\n            return await Client.SendAsync<");
            
            #line 81 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(\r\n                new ");
            
            #line 82 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Get()\r\n                {\r\n                    Id = Id\r\n                });\r\n     " +
                    "   }\r\n\r\n        public static async Task<");
            
            #line 88 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> GetCheckAsync(\r\n            JsonApiClient Client, ");
            
            #line 89 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TipoId));
            
            #line default
            #line hidden
            this.Write(" Id)\r\n        {\r\n            var o");
            
            #line 91 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" = await Client.SendAsync<");
            
            #line 91 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(\r\n                new ");
            
            #line 92 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Get()\r\n                {\r\n                    Id = Id\r\n                });\r\n\r\n   " +
                    "         WoGetExcepcion.CheckIfNullThenExcept(o");
            
            #line 97 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(", Id);\r\n\r\n            return o");
            
            #line 99 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        \r\n\r\n        public static ");
            
            #line 103 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Single(\r\n            JsonApiClient Client, ");
            
            #line 104 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Single SingleRequest)\r\n        {\r\n            return Client.Send<");
            
            #line 106 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(SingleRequest);\r\n        }\r\n\r\n        public static async Task<");
            
            #line 109 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> SingleAsync(\r\n            JsonApiClient Client, ");
            
            #line 110 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Single SingleRequest)\r\n        {\r\n            return await Client.SendAsync<");
            
            #line 112 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(SingleRequest);\r\n        }\r\n\r\n\r\n        public static ");
            
            #line 116 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Single(\r\n            JsonApiClient Client, ");
            
            #line 117 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TipoId));
            
            #line default
            #line hidden
            this.Write(" Id)\r\n        {\r\n            return Client.Send<");
            
            #line 119 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(\r\n                new ");
            
            #line 120 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Single()\r\n                {\r\n                    Id = Id\r\n                });\r\n  " +
                    "      }\r\n\r\n\r\n        public static ");
            
            #line 127 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" SingleCheck(\r\n            JsonApiClient Client, ");
            
            #line 128 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TipoId));
            
            #line default
            #line hidden
            this.Write(" Id)\r\n        {\r\n            var o");
            
            #line 130 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" = Client.Send<");
            
            #line 130 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(\r\n                new ");
            
            #line 131 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Single()\r\n                {\r\n                    Id = Id\r\n                });\r\n\r\n" +
                    "            WoGetExcepcion.CheckIfNullThenExcept(o");
            
            #line 136 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(", Id);\r\n\r\n            return o");
            
            #line 138 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n\r\n        public static async Task<");
            
            #line 141 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> SingleAsync(\r\n            JsonApiClient Client, ");
            
            #line 142 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TipoId));
            
            #line default
            #line hidden
            this.Write(" Id)\r\n        {\r\n            return await Client.SendAsync<");
            
            #line 144 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(\r\n                new ");
            
            #line 145 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Single()\r\n                {\r\n                    Id = Id\r\n                });\r\n  " +
                    "      }\r\n\r\n        public static async Task<");
            
            #line 151 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> SingleCheckAsync(\r\n            JsonApiClient Client, ");
            
            #line 152 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TipoId));
            
            #line default
            #line hidden
            this.Write(" Id)\r\n        {\r\n            var o");
            
            #line 154 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" = await Client.SendAsync<");
            
            #line 154 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(\r\n                new ");
            
            #line 155 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Single()\r\n                {\r\n                    Id = Id\r\n                });\r\n\r\n" +
                    "            WoGetExcepcion.CheckIfNullThenExcept(o");
            
            #line 160 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(", Id);\r\n\r\n            return o");
            
            #line 162 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n\r\n\r\n\r\n");
            
            #line 167 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
  bool bUniqueGet = (modelo.Columnas.Where( e => e.TipoDato == WoTypeData.UniqueGet ).FirstOrDefault() != null);
    if(bUniqueGet) 
    {
            
            #line default
            #line hidden
            this.Write("        public static ");
            
            #line 170 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" GetBy(\r\n            JsonApiClient Client, ");
            
            #line 171 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("GetBy GetByRequest)\r\n        {\r\n            return Client.Send<");
            
            #line 173 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(\r\n                new ");
            
            #line 174 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("GetBy()\r\n                {\r\n");
            
            #line 176 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
          foreach(ModeloColumna col in modelo.Columnas.Where( e => e.TipoDato == WoTypeData.UniqueGet ).OrderBy( e => e.Orden )) {

            
            #line default
            #line hidden
            this.Write("                   ");
            
            #line 178 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Id));
            
            #line default
            #line hidden
            this.Write(" = GetByRequest.");
            
            #line 178 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Id));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 179 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
          } 
            
            #line default
            #line hidden
            this.Write("                });\r\n        }\r\n\r\n        public static async Task<");
            
            #line 183 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> GetByAsync(\r\n            JsonApiClient Client, ");
            
            #line 184 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("GetBy GetByRequest)\r\n        {\r\n            return await Client.SendAsync<");
            
            #line 186 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(\r\n                new ");
            
            #line 187 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("GetBy()\r\n                {\r\n");
            
            #line 189 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
          foreach(ModeloColumna col in modelo.Columnas.Where( e => e.TipoDato == WoTypeData.UniqueGet ).OrderBy( e => e.Orden )) {

            
            #line default
            #line hidden
            this.Write("                   ");
            
            #line 191 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Id));
            
            #line default
            #line hidden
            this.Write(" = GetByRequest.");
            
            #line 191 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Id));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 192 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
          } 
            
            #line default
            #line hidden
            this.Write("                });\r\n        }\r\n");
            
            #line 195 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
  } 

    if ((modelo.TipoModelo != WoTypeModel.Configuration)
        && (modelo.TipoModelo != WoTypeModel.Control)
        && (modelo.TipoModelo != WoTypeModel.Kardex)
        && (modelo.TipoModelo != WoTypeModel.DataMart))
    { 
        foreach(Transicion tra in modelo.Diagrama.Transiciones.Where( e => e.EstadoInicial == 0 ))
    {
            
            #line default
            #line hidden
            this.Write("        public static ");
            
            #line 204 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Post(\r\n            JsonApiClient Client, ");
            
            #line 205 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 205 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" PostRequest)\r\n        {\r\n            return Client.Send<");
            
            #line 207 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PostRequest);\r\n        }\r\n\r\n        public static async Task<");
            
            #line 210 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> PostAsync(\r\n            JsonApiClient Client, ");
            
            #line 211 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 211 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" PostRequest)\r\n        {\r\n            return await Client.SendAsync<");
            
            #line 213 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PostRequest);\r\n        }\r\n\r\n");
            
            #line 216 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
  }

        foreach(Transicion tra in modelo.Diagrama.Transiciones.Where( e => e.EstadoInicial != 0 ) )
        {
            Estado estado = modelo.Diagrama.Estados.Where( es => es.NumId == tra.EstadoFinal ).FirstOrDefault();

            if(estado == null)
                throw new Exception($"No se encontró el estado {tra.EstadoFinal} para el modelo {modelo.Id} transición {tra.Id}");

            if(estado.Tipo == eEstadoTipo.FinalAlternativo) 
            {
            
            #line default
            #line hidden
            this.Write("        public static ");
            
            #line 227 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" SoftDelete(\r\n            JsonApiClient Client, ");
            
            #line 228 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 228 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" PatchRequest)\r\n        {\r\n            return Client.Put<");
            
            #line 230 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PatchRequest);\r\n        }\r\n\r\n        public static async Task<");
            
            #line 233 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> SoftDeleteAsync(\r\n            JsonApiClient Client, ");
            
            #line 234 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 234 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" PatchRequest)\r\n        {\r\n            return await Client.PutAsync<");
            
            #line 236 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PatchRequest);\r\n        }\r\n\r\n");
            
            #line 239 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
          }
            else
            { 
            
            #line default
            #line hidden
            this.Write("        public static ");
            
            #line 242 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Put(\r\n            JsonApiClient Client,  ");
            
            #line 243 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 243 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" PatchRequest)\r\n        {\r\n            return Client.Put<");
            
            #line 245 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PatchRequest);\r\n        }\r\n\r\n        public static ");
            
            #line 248 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Patch(\r\n            JsonApiClient Client,  ");
            
            #line 249 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 249 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" PatchRequest)\r\n        {\r\n            return Client.Patch<");
            
            #line 251 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PatchRequest);\r\n        }\r\n\r\n        public static async Task<");
            
            #line 254 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> PutAsync(\r\n            JsonApiClient Client, ");
            
            #line 255 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 255 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" PatchRequest)\r\n        {\r\n            return await Client.PutAsync<");
            
            #line 257 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PatchRequest);\r\n        }\r\n\r\n        public static async Task<");
            
            #line 260 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> PatchAsync(\r\n            JsonApiClient Client, ");
            
            #line 261 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 261 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" PatchRequest)\r\n        {\r\n            return await Client.PatchAsync<");
            
            #line 263 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PatchRequest);\r\n        }\r\n\r\n");
            
            #line 266 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
          }
        }
  
        foreach(Transicion tra in modelo.Diagrama.Transiciones.Where( e => e.EstadoInicial == 0 ) )
        {
            
            #line default
            #line hidden
            this.Write("        public static IList<");
            
            #line 271 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> Post(\r\n            JsonApiClient Client, IList<");
            
            #line 272 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 272 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write("> PostRequest)\r\n        {\r\n            return Client.SendAll<");
            
            #line 274 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PostRequest);\r\n        }\r\n\r\n        public static async Task<IList<");
            
            #line 277 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">> PostAsync(\r\n            JsonApiClient Client, IList<");
            
            #line 278 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 278 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write("> PostRequest)\r\n        {\r\n            return await Client.SendAllAsync<");
            
            #line 280 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PostRequest);\r\n        }\r\n");
            
            #line 282 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
      }

        foreach(Transicion tra in modelo.Diagrama.Transiciones.Where( e => e.EstadoInicial != 0 ) )
        {        
            Estado estado = modelo.Diagrama.Estados.Where( es => es.NumId == tra.EstadoFinal ).FirstOrDefault();

            if(estado == null)
                throw new Exception($"No se encontró el estado {tra.EstadoFinal} para el modelo {modelo.Id} transición {tra.Id}");

            if(estado.Tipo == eEstadoTipo.FinalAlternativo) 
            {
            
            #line default
            #line hidden
            this.Write("        public static IList<");
            
            #line 293 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> SoftDelete(\r\n            JsonApiClient Client, IList<");
            
            #line 294 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 294 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write("> PatchRequest)\r\n        {\r\n            return Client.SendAll<");
            
            #line 296 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PatchRequest);\r\n        }\r\n\r\n        public static async Task<IList<");
            
            #line 299 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">> SoftDeleteAsync(\r\n            JsonApiClient Client, IList<");
            
            #line 300 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 300 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write("> PatchRequest)\r\n        {\r\n            return await Client.SendAllAsync<");
            
            #line 302 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PatchRequest);\r\n        }\r\n\r\n");
            
            #line 305 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
          }
            else
            { 
            
            #line default
            #line hidden
            this.Write("        public static IList<");
            
            #line 308 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> Put(\r\n            JsonApiClient Client, IList<");
            
            #line 309 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 309 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write("> PatchRequest)\r\n        {\r\n            return Client.SendAll<");
            
            #line 311 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PatchRequest);\r\n        }\r\n\r\n        public static async Task<IList<");
            
            #line 314 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">> PutAsync(\r\n            JsonApiClient Client, IList<");
            
            #line 315 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 315 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write("> PatchRequest)\r\n        {\r\n            return await Client.SendAllAsync<");
            
            #line 317 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PatchRequest);\r\n        }\r\n");
            
            #line 319 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
          } 
        }

        if(modelo.bPostCondicionesExist) {
            foreach(Transicion tra in modelo.Diagrama.Transiciones.Where( e => ((modelo.TipoModelo == WoTypeModel.TransactionContable) && (e.EstadoFinal == 300)) ) ) {

            
            #line default
            #line hidden
            this.Write("        public static WoConPolizaRegistraYAfectar PolizaPrevia(\r\n            Json" +
                    "ApiClient Client, ");
            
            #line 326 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("PolizaPrevia GetRequest)\r\n        {\r\n            return Client.Send<WoConPolizaRe" +
                    "gistraYAfectar>(GetRequest);\r\n        }\r\n\r\n        public static async Task<WoCo" +
                    "nPolizaRegistraYAfectar> PolizaPreviaAsync(\r\n            JsonApiClient Client, ");
            
            #line 332 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("PolizaPrevia GetRequest)\r\n        {\r\n            return await Client.SendAsync<Wo" +
                    "ConPolizaRegistraYAfectar>(GetRequest);\r\n        }\r\n");
            
            #line 336 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
          }
		}
        if ((modelo.TipoModelo == WoTypeModel.CatalogType) ||
            (modelo.TipoModelo == WoTypeModel.Catalog)) 
        {  
            
            #line default
            #line hidden
            this.Write("\r\n        public static ");
            
            #line 342 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Delete(\r\n            JsonApiClient Client, ");
            
            #line 343 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TipoId));
            
            #line default
            #line hidden
            this.Write(" Id)\r\n        {\r\n            return Client.Delete<");
            
            #line 345 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(\r\n                new ");
            
            #line 346 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Borrar()\r\n                {\r\n                    Id = Id\r\n                });\r\n  " +
                    "      }\r\n\r\n        public static ");
            
            #line 352 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Delete(\r\n            JsonApiClient Client, ");
            
            #line 353 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Borrar PatchRequest)\r\n        {\r\n            return Client.Delete<");
            
            #line 355 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PatchRequest);\r\n        }\r\n\r\n        public static async Task<");
            
            #line 358 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> DeleteAsync(\r\n            JsonApiClient Client, ");
            
            #line 359 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Borrar PatchRequest)\r\n        {\r\n            return await Client.DeleteAsync<");
            
            #line 361 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PatchRequest);\r\n        }\r\n\r\n        public static IList<");
            
            #line 364 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("> Delete(\r\n            JsonApiClient Client, IList<");
            
            #line 365 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Borrar> PatchRequest)\r\n        {\r\n            return Client.SendAll<");
            
            #line 367 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PatchRequest);\r\n        }\r\n\r\n        public static async Task<IList<");
            
            #line 370 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">> DeleteAsync(\r\n            JsonApiClient Client, IList<");
            
            #line 371 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Borrar> PatchRequest)\r\n        {\r\n            return await Client.SendAllAsync<");
            
            #line 373 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(PatchRequest);\r\n        }\r\n");
            
            #line 375 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"
      }
    }

            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 380 "C:\Frog\WooW.SB.Config\Templates\ttModeloServicioCliente.tt"

public Modelo modelo { get; set; }  
public string TipoId { get; set; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class ttModeloServicioClienteBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
