// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del runtime: 17.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WooW.SB.Config.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using WooW.Core;
    using WooW.SB.Config;
    using WooW.SB.Config.Enum;
    using WooW.SB.Config.Helpers;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ttModeloDTO : ttModeloDTOBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttModeloDTO
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated> 
// ------------------------------------------------------------------------------//
using WooW.Core;
using WooW.Model;
using ServiceStack;
using ServiceStack.DataAnnotations;
using System.Collections.Generic;
using WooW.Resources.Labels;
using WooW.Resources.ModelData;
using WooW.Resources.ModelLabel;
using WooW.Resources.ModelComment;
using Newtonsoft.Json;

namespace WooW.DTO
{


#if DEBUG
#if SERVER");
            
            #line 35 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.GetRolesList()));
            
            #line default
            #line hidden
            this.Write("\r\n#endif\r\n    [ValidateIsAuthenticated]\r\n    [Tag(\"");
            
            #line 38 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("s\")]\r\n    [Route(\"/api/");
            
            #line 39 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("AutoQuery\", \"GET\")]\r\n    [JsonObject(MemberSerialization.OptOut)]\r\n    public cla" +
                    "ss ");
            
            #line 41 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("AutoQuery : QueryDb<");
            
            #line 41 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">, IWoInstanciaUdn\r\n    {\r\n    }\r\n#endif\r\n\r\n    #if SERVER");
            
            #line 46 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.GetRolesList()));
            
            #line default
            #line hidden
            this.Write("\r\n    [AutoApply(Behavior.AuditQuery)]\r\n    #endif\r\n    [ValidateIsAuthenticated]" +
                    "\r\n    [Tag(\"");
            
            #line 50 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("s\")]\r\n    [Route(\"/api/");
            
            #line 51 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("List\", \"GET\")]\r\n    [JsonObject(MemberSerialization.OptOut)]\r\n    public class ");
            
            #line 53 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(@"List : IWoInstanciaUdn, IWoODataRequest
    {
        public string select { get; set; }
        public string filter { get; set; }
        public string orderby { get; set; }
        public bool count { get; set; }
        public int? top { get; set; }
        public int? skip { get; set; }
        public bool withref { get; set; }
        public string totalizer { get; set; }
    }

    #if SERVER");
            
            #line 65 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.GetRolesList()));
            
            #line default
            #line hidden
            this.Write("\r\n    [AutoApply(Behavior.AuditQuery)]\r\n    #endif\r\n    [ValidateIsAuthenticated]" +
                    "\r\n    [Tag(\"");
            
            #line 69 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("s\")]\r\n    [Route(\"/api/");
            
            #line 70 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Get\", \"GET\")]\r\n    [JsonObject(MemberSerialization.OptOut)]\r\n    public class ");
            
            #line 72 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Get : IWoInstanciaUdn\r\n    {\r\n        public ");
            
            #line 74 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TipoId));
            
            #line default
            #line hidden
            this.Write(" Id { get; set; }\r\n    }\r\n\r\n    #if SERVER");
            
            #line 77 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.GetRolesList()));
            
            #line default
            #line hidden
            this.Write("\r\n    [AutoApply(Behavior.AuditQuery)]\r\n    #endif\r\n    [ValidateIsAuthenticated]" +
                    "\r\n    [Tag(\"");
            
            #line 81 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("s\")]\r\n    [Route(\"/api/");
            
            #line 82 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Single\", \"GET\")]\r\n    [JsonObject(MemberSerialization.OptOut)]\r\n    public class " +
                    "");
            
            #line 84 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Single : IWoInstanciaUdn\r\n    {\r\n        public ");
            
            #line 86 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TipoId));
            
            #line default
            #line hidden
            this.Write(" Id { get; set; }\r\n    }\r\n\r\n");
            
            #line 89 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
  bool bUniqueGet = (modelo.Columnas.Where( e => e.TipoDato == WoTypeData.UniqueGet ).FirstOrDefault() != null);
    if(bUniqueGet) 
    {
            
            #line default
            #line hidden
            this.Write("    #if SERVER");
            
            #line 92 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.GetRolesList()));
            
            #line default
            #line hidden
            this.Write("\r\n    [AutoApply(Behavior.AuditQuery)]\r\n    #endif\r\n    [ValidateIsAuthenticated]" +
                    "\r\n    [Tag(\"");
            
            #line 96 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("s\")]\r\n    [Route(\"/api/");
            
            #line 97 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("GetBy\", \"GETBY\")]\r\n    [JsonObject(MemberSerialization.OptOut)]\r\n    public class" +
                    " ");
            
            #line 99 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("GetBy : IWoInstanciaUdn\r\n    {\r\n");
            
            #line 101 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      foreach(ModeloColumna col in modelo.Columnas.Where( e => e.TipoDato == WoTypeData.UniqueGet ).OrderBy( e => e.Orden )) {
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 102 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ToPropertyDTO(modelo, false)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 103 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      } 
            
            #line default
            #line hidden
            this.Write("    }\r\n");
            
            #line 105 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 107 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
  foreach(Transicion tra in modelo.Diagrama.Transiciones.Where( e => e.EstadoInicial == 0 ) )
    {
            
            #line default
            #line hidden
            this.Write("  \r\n    #if SERVER\r\n    [AutoApply(Behavior.AuditCreate)]");
            
            #line 110 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.GetRolesTra(tra)));
            
            #line default
            #line hidden
            
            #line 110 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.GetPermisos()));
            
            #line default
            #line hidden
            this.Write("\r\n    #endif\r\n    [ValidateIsAuthenticated]\r\n    [Tag(\"");
            
            #line 113 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("s\")]\r\n    [Route(\"/api/");
            
            #line 114 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 114 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write("\", \"POST\")]\r\n    [AutoPopulate(nameof(");
            
            #line 115 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(".WoState), Value = e");
            
            #line 115 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("_WoState.");
            
            #line 115 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Diagrama.EstadoByNum(tra.EstadoFinal)));
            
            #line default
            #line hidden
            this.Write(")]\r\n    [WoModelBase(typeof(");
            
            #line 116 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("))]\r\n    [JsonObject(MemberSerialization.OptOut)]\r\n    public class ");
            
            #line 118 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 118 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" : IWoInstanciaUdn, IReturn<");
            
            #line 118 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        public ");
            
            #line 120 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 120 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n");
            
            #line 122 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
  foreach(ModeloColumna col in modelo.Columnas.Where( e => (!string.IsNullOrEmpty(e.Default))))  {
            var found = tra.DTO.Columnas.Where( e => e == col.Id ).FirstOrDefault();
            if(found == null)
                continue;
    
            
            #line default
            #line hidden
            
            #line 127 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ToDefault()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 128 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
  }
            
            #line default
            #line hidden
            
            #line 129 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      foreach(var coll in tra.DTO.Colleccion )
        {
            if((!coll.Insertar) && (!coll.Actualizar) && (!coll.Borrar))
                continue;

            var modeloSlave = proyecto.ModeloCol.Modelos.Where( t => t.Id == coll.ModeloId ).FirstOrDefault();
            if(modeloSlave == null)
                continue;

            ModeloColumna colloc = modelo.Columnas.Where(e => e.Id == modeloSlave.Id + "Col").FirstOrDefault();
            if(colloc != null)
            {
            
            #line default
            #line hidden
            
            #line 141 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(colloc.ToCollectionDefault(tra.Id)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 142 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
          }
        }
            
            #line default
            #line hidden
            this.Write("  \r\n        }\r\n\r\n");
            
            #line 146 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      foreach(ModeloColumna col in modelo.Columnas.OrderBy( e => e.Orden ) ) {
            var found = tra.DTO.Columnas.Where( e => e == col.Id ).FirstOrDefault();
            if(found == null)
                continue;
            var foundNoEditar = tra.DTO.ColumnasNoEditar.Where( e => e == col.Id ).FirstOrDefault();
            if((col.TipoColumna == WoTypeColumn.Reference) && (col.EsColeccion))
                continue;
        
            
            #line default
            #line hidden
            
            #line 154 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ToAttributesDTO()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 155 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      if(foundNoEditar != null)
        {
            
            #line default
            #line hidden
            this.Write("        [WoNoEditar]\r\n");
            
            #line 158 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      }
            
            #line default
            #line hidden
            
            #line 159 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ToPropertyDTO(modelo, false)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 160 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      }
        foreach(var coll in tra.DTO.Colleccion )
        {
            if((!coll.Insertar) && (!coll.Actualizar) && (!coll.Borrar))
                continue;

            var modeloSlave = proyecto.ModeloCol.Modelos.Where( t => t.Id == coll.ModeloId ).FirstOrDefault();
            if(modeloSlave == null)
                continue;

            ModeloColumna colloc = modelo.Columnas.Where(e => e.Id == modeloSlave.Id + "Col").FirstOrDefault();
            if(colloc != null)
            {
            
            #line default
            #line hidden
            
            #line 173 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(colloc.ToAttributesDTO()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 174 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
          }
            
            #line default
            #line hidden
            this.Write("  \r\n        [Reference]\r\n");
            
            #line 176 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
          if(coll.Insertar) {
            
            #line default
            #line hidden
            this.Write("        [WoSlaveAllowInsert]\r\n");
            
            #line 178 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
           }
            
            #line default
            #line hidden
            
            #line 179 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
          if(coll.Actualizar) {
            
            #line default
            #line hidden
            this.Write("        [WoSlaveAllowUpdate]\r\n");
            
            #line 181 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
           }
            
            #line default
            #line hidden
            
            #line 182 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
          if(coll.Borrar) {
            
            #line default
            #line hidden
            this.Write("        [WoSlaveAllowDelete]\r\n");
            
            #line 184 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
           }
            
            #line default
            #line hidden
            this.Write("        [WoModelBase(typeof(");
            
            #line 185 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("))]\r\n        public virtual IList<");
            
            #line 186 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modeloSlave.Id));
            
            #line default
            #line hidden
            
            #line 186 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 186 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modeloSlave.Id));
            
            #line default
            #line hidden
            this.Write("Col { get; set; }\r\n");
            
            #line 187 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      }

            
            #line default
            #line hidden
            this.Write("\r\n    }\r\n");
            
            #line 191 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
  }
            
            #line default
            #line hidden
            this.Write("  \r\n\r\n");
            
            #line 193 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
  foreach(Transicion tra in modelo.Diagrama.Transiciones.Where( e => e.EstadoInicial != 0 ) )
    {
            
            #line default
            #line hidden
            this.Write("  \r\n    #if SERVER\r\n    [AutoApply(Behavior.AuditModify)]");
            
            #line 196 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.GetRolesTra(tra)));
            
            #line default
            #line hidden
            
            #line 196 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.GetPermisos()));
            
            #line default
            #line hidden
            this.Write("\r\n    #endif\r\n    [ValidateIsAuthenticated]\r\n    [Tag(\"");
            
            #line 199 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("s\")]\r\n    [Route(\"/api/");
            
            #line 200 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 200 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write("\", \"PUT PATCH\")]\r\n    [AutoPopulate(nameof(");
            
            #line 201 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(".WoState), Value = e");
            
            #line 201 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("_WoState.");
            
            #line 201 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Diagrama.EstadoByNum(tra.EstadoFinal)));
            
            #line default
            #line hidden
            this.Write(")]\r\n    [WoModelBase(typeof(");
            
            #line 202 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("))]\r\n    [JsonObject(MemberSerialization.OptOut)]\r\n    public class ");
            
            #line 204 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 204 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" : IWoInstanciaUdn, IReturn<");
            
            #line 204 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n");
            
            #line 206 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      foreach(ModeloColumna col in modelo.Columnas.OrderBy( e => e.Orden ) ) {
            var found = tra.DTO.Columnas.Where( e => e == col.Id ).FirstOrDefault();
            if(found == null)
                continue;
            var foundNoEditar = tra.DTO.ColumnasNoEditar.Where( e => e == col.Id ).FirstOrDefault();
            if((col.TipoColumna == WoTypeColumn.Reference) && (col.EsColeccion))
                continue;

            
            #line default
            #line hidden
            
            #line 214 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ToAttributesDTO()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 215 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      if(foundNoEditar != null)
        {
            
            #line default
            #line hidden
            this.Write("        [WoNoEditar]\r\n");
            
            #line 218 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
     }
            
            #line default
            #line hidden
            
            #line 219 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ToPropertyDTO(modelo, true)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 220 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      }

        foreach(var coll in tra.DTO.Colleccion )
        {
            if((!coll.Insertar) && (!coll.Actualizar) && (!coll.Borrar))
                continue;

            var modeloSlave = proyecto.ModeloCol.Modelos.Where( t => t.Id == coll.ModeloId ).FirstOrDefault();
            if(modeloSlave == null)
                continue;

            ModeloColumna colloc = modelo.Columnas.Where(e => e.Id == modeloSlave.Id + "Col").FirstOrDefault();
            if(colloc != null)
            {
            
            #line default
            #line hidden
            
            #line 234 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(colloc.ToAttributesDTO()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 235 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
          }
            
            #line default
            #line hidden
            this.Write("  \r\n        [Reference]\r\n        [WoReferenceBase(typeof(");
            
            #line 237 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("))]\r\n");
            
            #line 238 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
          if(coll.Insertar) {
            
            #line default
            #line hidden
            this.Write("        [WoSlaveAllowInsert]\r\n");
            
            #line 240 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
           }
            
            #line default
            #line hidden
            
            #line 241 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
          if(coll.Actualizar) {
            
            #line default
            #line hidden
            this.Write("        [WoSlaveAllowUpdate]\r\n");
            
            #line 243 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
           }
            
            #line default
            #line hidden
            
            #line 244 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
          if(coll.Borrar) {
            
            #line default
            #line hidden
            this.Write("        [WoSlaveAllowDelete]\r\n");
            
            #line 246 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
           }
            
            #line default
            #line hidden
            this.Write("        public virtual IList<");
            
            #line 247 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modeloSlave.Id));
            
            #line default
            #line hidden
            
            #line 247 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 247 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modeloSlave.Id));
            
            #line default
            #line hidden
            this.Write("Col { get; set; }\r\n");
            
            #line 248 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      }

            
            #line default
            #line hidden
            this.Write("\r\n    }\r\n\r\n");
            
            #line 253 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
  }
            
            #line default
            #line hidden
            this.Write("  \r\n\r\n");
            
            #line 255 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
  foreach(Transicion tra in modelo.Diagrama.Transiciones )
    {
        foreach(var coll in tra.DTO.Colleccion )
        {
            if((!coll.Insertar) && (!coll.Actualizar) && (!coll.Borrar))
                continue;

            var modeloSlave = proyecto.ModeloCol.Modelos.Where( t => t.Id == coll.ModeloId ).FirstOrDefault();
            if(modeloSlave == null)
                continue;
    
            
            #line default
            #line hidden
            this.Write("  \r\n    [WoModelBase(typeof(");
            
            #line 266 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modeloSlave.Id));
            
            #line default
            #line hidden
            this.Write("))]\r\n    [JsonObject(MemberSerialization.OptOut)]\r\n    public class ");
            
            #line 268 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modeloSlave.Id));
            
            #line default
            #line hidden
            
            #line 268 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" : IWoTypeOfSlaveDTO\r\n    {\r\n        public ");
            
            #line 270 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modeloSlave.Id));
            
            #line default
            #line hidden
            
            #line 270 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n");
            
            #line 272 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
  foreach(ModeloColumna col in modeloSlave.Columnas.Where( e => (!string.IsNullOrEmpty(e.Default)) || e.EsColeccion))  {
                var found = coll.Columnas.Where( e => e == col.Id ).FirstOrDefault();
                if(found == null)
                    continue;
        if(col.EsColeccion)
        {
            
            #line default
            #line hidden
            
            #line 278 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ToCollectionDefault(string.Empty)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 279 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      }
        else 
        {
            
            #line default
            #line hidden
            
            #line 282 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ToDefault()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 283 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      }
     }
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n");
            
            #line 287 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
          foreach(ModeloColumna col in modeloSlave.Columnas.OrderBy( e => e.Orden ) ) {
                var found = coll.Columnas.Where( e => e == col.Id ).FirstOrDefault();
                if(found == null)
                    continue;
                var foundNoEditar = coll.ColumnasNoEditar.Where( e => e == col.Id ).FirstOrDefault();

            
            #line default
            #line hidden
            
            #line 293 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ToAttributesDTO()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 294 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      if(foundNoEditar != null)
        {
            
            #line default
            #line hidden
            this.Write("        [WoNoEditar]\r\n");
            
            #line 297 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      }
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 298 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ToPropertyDTO(modeloSlave, true)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 299 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      }
            
            #line default
            #line hidden
            this.Write("    }\r\n");
            
            #line 301 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      }
    }

    if(modelo.bPostCondicionesExist)
    {
        foreach(Transicion tra in modelo.Diagrama.Transiciones.Where( e => ((modelo.TipoModelo == WoTypeModel.TransactionContable) && (e.EstadoFinal == 300)) ))  // Contabilizado
        {
            
            #line default
            #line hidden
            this.Write("    #if SERVER");
            
            #line 308 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.GetRolesTra(tra)));
            
            #line default
            #line hidden
            this.Write("\r\n#endif\r\n    [ValidateIsAuthenticated]\r\n    [Tag(\"");
            
            #line 311 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("s\")]\r\n    [Route(\"/api/");
            
            #line 312 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("PolizaPrevia\")]\r\n    [JsonObject(MemberSerialization.OptOut)]\r\n    public class ");
            
            #line 314 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("PolizaPrevia : IWoInstanciaUdn\r\n    {\r\n        public string Id { get; set; }\r\n  " +
                    "  }\r\n\r\n");
            
            #line 319 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
   }
}
            
            #line default
            #line hidden
            this.Write("  \r\n");
            
            #line 321 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      if ((modelo.TipoModelo == WoTypeModel.CatalogType) ||
            (modelo.TipoModelo == WoTypeModel.Catalog) ||
            (modelo.TipoModelo == WoTypeModel.Control) ||
            (modelo.TipoModelo == WoTypeModel.DataMart))
        {
            
            #line default
            #line hidden
            this.Write("#if SERVER");
            
            #line 326 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.GetRoles()));
            
            #line default
            #line hidden
            this.Write("\r\n    [RequiresAnyPermission(nameof(Permiso.WoCatalogoBorrar))]\r\n#endif\r\n    [Val" +
                    "idateIsAuthenticated]\r\n    [Tag(\"");
            
            #line 330 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("s\")]\r\n    [Route(\"/api/");
            
            #line 331 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Borrar\", \"DELETE\")]\r\n    [JsonObject(MemberSerialization.OptOut)]\r\n    public cla" +
                    "ss ");
            
            #line 333 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Borrar : IWoInstanciaUdn, IReturn<");
            
            #line 333 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        public ");
            
            #line 335 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TipoId));
            
            #line default
            #line hidden
            this.Write(" Id { get; set; }\r\n    }\r\n");
            
            #line 337 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"
      }
            
            #line default
            #line hidden
            this.Write("  \r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 339 "C:\Frog\WooW.SB.Config\Templates\ttModeloDTO.tt"

public Modelo modelo { get; set; }  
public string TipoId { get; set; }
public Proyecto proyecto { get; set; }  

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class ttModeloDTOBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
