// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WooW.SB.Config.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using WooW.Core;
    using WooW.SB.Config;
    using WooW.SB.Config.Enum;
    using WooW.SB.UI.EnumExtension;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ttModeloServicioParametro : ttModeloServicioParametroBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttModeloServicioParametro
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using WooW.Core.Server;
using WooW.Core;
using WooW.Core.Common;
using WooW.DTO;
using ServiceStack;
using ServiceStack.OrmLite;
using System.Collections.Generic;

namespace WooW.Model
{
    public partial class ");
            
            #line 29 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n\r\n        public static ");
            
            #line 32 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Get(WoTargetConnection woTarget)\r\n        {\r\n            return ");
            
            #line 34 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(".Get(woTarget, WoGetFlags.None | WoGetFlags.ApplyFilter);\r\n        }  \r\n\r\n       " +
                    " public static ");
            
            #line 37 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Get(WoTargetConnection woTarget, WoGetFlags woGetFlags)\r\n        {\r\n            " +
                    "return WoGenericService.Get<");
            
            #line 39 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(woTarget, woGetFlags | WoGetFlags.ApplyFilter);\r\n        }  \r\n\r\n        public " +
                    "static ");
            
            #line 42 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Single(WoTargetConnection woTarget)\r\n        {\r\n            return ");
            
            #line 44 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(".Single(woTarget, WoGetFlags.None | WoGetFlags.ApplyFilter);\r\n        }  \r\n\r\n    " +
                    "    public static ");
            
            #line 47 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Single(WoTargetConnection woTarget, WoGetFlags woGetFlags)\r\n        {\r\n         " +
                    "   return WoGenericService.Single<");
            
            #line 49 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(woTarget, woGetFlags | WoGetFlags.ApplyFilter);\r\n        }  \r\n\r\n");
            
            #line 52 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
  foreach(Transicion tra in modelo.Diagrama.Transiciones.Where( e => e.EstadoInicial == 0 ) )
    {
            
            #line default
            #line hidden
            this.Write("        public static ");
            
            #line 54 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Post(WoTargetConnection woTarget, ");
            
            #line 54 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 54 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" dtoRequest)\r\n        {\r\n");
            
            #line 56 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          foreach(var preconditionsFile in PreConditionsFiles) {
            
            #line default
            #line hidden
            this.Write("            var Pre");
            
            #line 57 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(preconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 57 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("PreConditions");
            
            #line 57 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(preconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write("(woTarget);\r\n");
            
            #line 58 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          }
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 60 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          foreach(var postconditionsFile in PostConditionsFiles) {
            
            #line default
            #line hidden
            this.Write("            var Post");
            
            #line 61 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(postconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 61 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("PostConditions");
            
            #line 61 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(postconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write("(woTarget);\r\n");
            
            #line 62 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          }
            
            #line default
            #line hidden
            this.Write("\r\n            return ");
            
            #line 64 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WoGenericService));
            
            #line default
            #line hidden
            this.Write(".Post<");
            
            #line 64 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 64 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 64 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(woTarget, dtoRequest,\r\n                (int)e");
            
            #line 65 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("_WoState.");
            
            #line 65 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Diagrama.EstadoByNum(tra.EstadoFinal)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 66 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          if(PreConditionsFiles.Count > 0) {
            
            #line default
            #line hidden
            this.Write("                [\r\n");
            
            #line 68 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
              foreach(var preconditionsFile in PreConditionsFiles) {
            
            #line default
            #line hidden
            this.Write("                    Pre");
            
            #line 69 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(preconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 69 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 69 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 70 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
              } 
            
            #line default
            #line hidden
            this.Write("                ],\r\n");
            
            #line 72 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          } else { 
            
            #line default
            #line hidden
            this.Write("                null,\r\n");
            
            #line 74 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          }
            
            #line default
            #line hidden
            
            #line 75 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          if(PostConditionsFiles.Count > 0) {
            
            #line default
            #line hidden
            this.Write("                [\r\n");
            
            #line 77 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
              foreach(var postconditionsFile in PostConditionsFiles) {
            
            #line default
            #line hidden
            this.Write("                    Post");
            
            #line 78 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(postconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 78 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 78 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 79 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
              } 
            
            #line default
            #line hidden
            this.Write("                ]);\r\n");
            
            #line 81 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          } else { 
            
            #line default
            #line hidden
            this.Write("                null);\r\n");
            
            #line 83 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          }
            
            #line default
            #line hidden
            this.Write("        }\r\n");
            
            #line 85 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
  }

            
            #line default
            #line hidden
            
            #line 87 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
  foreach(Transicion tra in modelo.Diagrama.Transiciones.Where( e => e.EstadoInicial != 0 ) )
    {
        Estado estado = modelo.Diagrama.Estados.Where( es => es.NumId == tra.EstadoFinal ).FirstOrDefault();

        if(estado == null)
            throw new Exception($"No se encontró el estado {tra.EstadoFinal} para el modelo {modelo.Id} transición {tra.Id}");

        if(estado.Tipo == eEstadoTipo.FinalAlternativo) 
        {
            
            #line default
            #line hidden
            this.Write("        public static ");
            
            #line 96 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" SoftDelete(WoTargetConnection woTarget, ");
            
            #line 96 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 96 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" dtoRequest)\r\n        {\r\n");
            
            #line 98 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          foreach(var preconditionsFile in PreConditionsFiles) {
            
            #line default
            #line hidden
            this.Write("            var Pre");
            
            #line 99 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(preconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 99 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("PreConditions");
            
            #line 99 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(preconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write("(woTarget);\r\n");
            
            #line 100 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          }
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 102 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          foreach(var postconditionsFile in PostConditionsFiles) {
            
            #line default
            #line hidden
            this.Write("            var Post");
            
            #line 103 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(postconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 103 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("PostConditions");
            
            #line 103 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(postconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write("(woTarget);\r\n");
            
            #line 104 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          }
            
            #line default
            #line hidden
            this.Write("\r\n            return ");
            
            #line 106 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WoGenericService));
            
            #line default
            #line hidden
            this.Write(".SoftDelete<");
            
            #line 106 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 106 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 106 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(woTarget, dtoRequest,\r\n                (int)e");
            
            #line 107 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("_WoState.");
            
            #line 107 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Diagrama.EstadoByNum(tra.EstadoInicial)));
            
            #line default
            #line hidden
            this.Write(", (int)e");
            
            #line 107 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("_WoState.");
            
            #line 107 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Diagrama.EstadoByNum(tra.EstadoFinal)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 108 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          if(PreConditionsFiles.Count > 0) {
            
            #line default
            #line hidden
            this.Write("                [\r\n");
            
            #line 110 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
              foreach(var preconditionsFile in PreConditionsFiles) {
            
            #line default
            #line hidden
            this.Write("                    Pre");
            
            #line 111 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(preconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 111 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 111 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 112 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
              } 
            
            #line default
            #line hidden
            this.Write("                ],\r\n");
            
            #line 114 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          } else { 
            
            #line default
            #line hidden
            this.Write("                null,\r\n");
            
            #line 116 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          }
            
            #line default
            #line hidden
            
            #line 117 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          if(PostConditionsFiles.Count > 0) {
            
            #line default
            #line hidden
            this.Write("                [\r\n");
            
            #line 119 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
              foreach(var postconditionsFile in PostConditionsFiles) {
            
            #line default
            #line hidden
            this.Write("                    Post");
            
            #line 120 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(postconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 120 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 120 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 121 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
              } 
            
            #line default
            #line hidden
            this.Write("                ]);\r\n");
            
            #line 123 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          } else { 
            
            #line default
            #line hidden
            this.Write("                null);\r\n");
            
            #line 125 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          }
            
            #line default
            #line hidden
            this.Write("        }\r\n");
            
            #line 127 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
      }
        else
        { 
            
            #line default
            #line hidden
            this.Write("        public static ");
            
            #line 130 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Put(WoTargetConnection woTarget, ");
            
            #line 130 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 130 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" dtoRequest)\r\n        {\r\n");
            
            #line 132 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          foreach(var preconditionsFile in PreConditionsFiles) {
            
            #line default
            #line hidden
            this.Write("            var Pre");
            
            #line 133 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(preconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 133 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("PreConditions");
            
            #line 133 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(preconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write("(woTarget);\r\n");
            
            #line 134 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          }
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 136 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          foreach(var postconditionsFile in PostConditionsFiles) {
            
            #line default
            #line hidden
            this.Write("            var Post");
            
            #line 137 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(postconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 137 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("PostConditions");
            
            #line 137 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(postconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write("(woTarget);\r\n");
            
            #line 138 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          }
            
            #line default
            #line hidden
            this.Write("\r\n            return ");
            
            #line 140 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WoGenericService));
            
            #line default
            #line hidden
            this.Write(".PutPatch<");
            
            #line 140 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 140 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 140 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(woTarget, dtoRequest, woModifyVerb.Put,\r\n                (int)e");
            
            #line 141 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("_WoState.");
            
            #line 141 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Diagrama.EstadoByNum(tra.EstadoInicial)));
            
            #line default
            #line hidden
            this.Write(", (int)e");
            
            #line 141 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("_WoState.");
            
            #line 141 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Diagrama.EstadoByNum(tra.EstadoFinal)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 142 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          if(PreConditionsFiles.Count > 0) {
            
            #line default
            #line hidden
            this.Write("                [\r\n");
            
            #line 144 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
              foreach(var preconditionsFile in PreConditionsFiles) {
            
            #line default
            #line hidden
            this.Write("                    Pre");
            
            #line 145 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(preconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 145 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 145 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 146 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
              } 
            
            #line default
            #line hidden
            this.Write("                ],\r\n");
            
            #line 148 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          } else { 
            
            #line default
            #line hidden
            this.Write("                null,\r\n");
            
            #line 150 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          }
            
            #line default
            #line hidden
            
            #line 151 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          if(PostConditionsFiles.Count > 0) {
            
            #line default
            #line hidden
            this.Write("                [\r\n");
            
            #line 153 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
              foreach(var postconditionsFile in PostConditionsFiles) {
            
            #line default
            #line hidden
            this.Write("                    Post");
            
            #line 154 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(postconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 154 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 154 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 155 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
              } 
            
            #line default
            #line hidden
            this.Write("                ]);\r\n");
            
            #line 157 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          } else { 
            
            #line default
            #line hidden
            this.Write("                null);\r\n");
            
            #line 159 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          }
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public static ");
            
            #line 162 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Patch(WoTargetConnection woTarget, ");
            
            #line 162 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 162 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(" dtoRequest)\r\n        {\r\n");
            
            #line 164 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          foreach(var preconditionsFile in PreConditionsFiles) {
            
            #line default
            #line hidden
            this.Write("            var Pre");
            
            #line 165 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(preconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 165 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("PreConditions");
            
            #line 165 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(preconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write("(woTarget);\r\n");
            
            #line 166 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          }
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 168 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          foreach(var postconditionsFile in PostConditionsFiles) {
            
            #line default
            #line hidden
            this.Write("            var Post");
            
            #line 169 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(postconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 169 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("PostConditions");
            
            #line 169 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(postconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write("(woTarget);\r\n");
            
            #line 170 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          }
            
            #line default
            #line hidden
            this.Write("\r\n            return ");
            
            #line 172 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WoGenericService));
            
            #line default
            #line hidden
            this.Write(".PutPatch<");
            
            #line 172 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 172 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 172 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(">(woTarget, dtoRequest, woModifyVerb.Patch,\r\n                (int)e");
            
            #line 173 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("_WoState.");
            
            #line 173 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Diagrama.EstadoByNum(tra.EstadoInicial)));
            
            #line default
            #line hidden
            this.Write(", (int)e");
            
            #line 173 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("_WoState.");
            
            #line 173 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Diagrama.EstadoByNum(tra.EstadoFinal)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 174 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          if(PreConditionsFiles.Count > 0) {
            
            #line default
            #line hidden
            this.Write("                [\r\n");
            
            #line 176 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
              foreach(var preconditionsFile in PreConditionsFiles) {
            
            #line default
            #line hidden
            this.Write("                    Pre");
            
            #line 177 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(preconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 177 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 177 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 178 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
              } 
            
            #line default
            #line hidden
            this.Write("                ],\r\n");
            
            #line 180 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          } else { 
            
            #line default
            #line hidden
            this.Write("                null,\r\n");
            
            #line 182 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          }
            
            #line default
            #line hidden
            
            #line 183 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          if(PostConditionsFiles.Count > 0) {
            
            #line default
            #line hidden
            this.Write("                [\r\n");
            
            #line 185 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
              foreach(var postconditionsFile in PostConditionsFiles) {
            
            #line default
            #line hidden
            this.Write("                    Post");
            
            #line 186 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(postconditionsFile.Item1));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 186 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            
            #line 186 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tra.Id));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 187 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
              } 
            
            #line default
            #line hidden
            this.Write("                ]);\r\n");
            
            #line 189 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          } else { 
            
            #line default
            #line hidden
            this.Write("                null);\r\n");
            
            #line 191 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
          }
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n");
            
            #line 194 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"
      }
    }
            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 198 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioParametro.tt"

public Modelo modelo { get; set; }  
public string WoGenericService { get; set; }  
public List<Tuple<string, string>> PreConditionsFiles { get; set; }  
public List<Tuple<string, string>> PostConditionsFiles { get; set; }  

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class ttModeloServicioParametroBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
