// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WooW.SB.Config.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using WooW.Core;
    using WooW.SB.Config;
    using WooW.SB.Config.Enum;
    using WooW.SB.UI.EnumExtension;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ttModeloServicioRequest : ttModeloServicioRequestBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttModeloServicioRequest
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
");
            
            #line 19 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
  
    if (modelo.ScriptRequest.Coleccion) { 
        locResponse = $"IList<{responseObject}>";
    } else {
        locResponse = $"{responseObject}";
    }

            
            #line default
            #line hidden
            this.Write("using WooW.Core.Server;\r\nusing WooW.Core;\r\nusing WooW.DTO;\r\nusing ServiceStack;\r\n" +
                    "using ServiceStack.OrmLite;\r\nusing System.Collections.Generic;\r\n\r\nnamespace WooW" +
                    ".Model\r\n{\r\n    public partial class ");
            
            #line 35 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n\r\n");
            
            #line 38 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
 if (modelo.ScriptRequest.EjecutarEnBackGround){ 
            
            #line default
            #line hidden
            this.Write("        public static ");
            
            #line 39 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(locResponse));
            
            #line default
            #line hidden
            this.Write(" Do(WoTargetConnection woTarget, ");
            
            #line 39 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Request)\r\n        {\r\n            ");
            
            #line 41 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Script Script = new ");
            
            #line 41 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Script();\r\n\r\n            return Script.");
            
            #line 43 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Do<");
            
            #line 43 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 43 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.ScriptRequest.ResponseId));
            
            #line default
            #line hidden
            this.Write(">(\r\n                woTarget, Request);\r\n        }\r\n");
            
            #line 46 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
 }
   else
   {
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 50 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
 if (modelo.ScriptRequest.UsaGetEnRequest){ 
            
            #line default
            #line hidden
            this.Write("        public static ");
            
            #line 51 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(locResponse));
            
            #line default
            #line hidden
            this.Write(" Get(WoTargetConnection woTarget, ");
            
            #line 51 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Request)\r\n        {\r\n            ");
            
            #line 53 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Script Script = new ");
            
            #line 53 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Script();\r\n\r\n            return Script.");
            
            #line 55 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Get<");
            
            #line 55 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 55 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.ScriptRequest.ResponseId));
            
            #line default
            #line hidden
            this.Write(">(\r\n                woTarget, Request);\r\n        }\r\n");
            
            #line 58 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
 }
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 60 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
 if (modelo.ScriptRequest.UsaPostEnRequest){ 
            
            #line default
            #line hidden
            this.Write("        public static ");
            
            #line 61 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(locResponse));
            
            #line default
            #line hidden
            this.Write(" Post(WoTargetConnection woTarget, ");
            
            #line 61 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Request)\r\n        {\r\n            ");
            
            #line 63 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Script Script = new ");
            
            #line 63 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Script();\r\n\r\n            return Script.");
            
            #line 65 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Post<");
            
            #line 65 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 65 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.ScriptRequest.ResponseId));
            
            #line default
            #line hidden
            this.Write(">(\r\n                woTarget, Request);\r\n        }\r\n");
            
            #line 68 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
 }
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 70 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
 if (modelo.ScriptRequest.UsaPutEnRequest){ 
            
            #line default
            #line hidden
            this.Write("        public static ");
            
            #line 71 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(locResponse));
            
            #line default
            #line hidden
            this.Write(" Put(WoTargetConnection woTarget, ");
            
            #line 71 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Request)\r\n        {\r\n            ");
            
            #line 73 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Script Script = new ");
            
            #line 73 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Script();\r\n\r\n            return Script.");
            
            #line 75 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Put<");
            
            #line 75 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 75 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.ScriptRequest.ResponseId));
            
            #line default
            #line hidden
            this.Write(">(\r\n                woTarget, Request);\r\n        }\r\n");
            
            #line 78 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
 }
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 80 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
 if (modelo.ScriptRequest.UsaPatchEnRequest){ 
            
            #line default
            #line hidden
            this.Write("        public static ");
            
            #line 81 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(locResponse));
            
            #line default
            #line hidden
            this.Write(" Patch(WoTargetConnection woTarget, ");
            
            #line 81 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Request)\r\n        {\r\n            ");
            
            #line 83 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Script Script = new ");
            
            #line 83 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Script();\r\n\r\n            return Script.");
            
            #line 85 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Patch<");
            
            #line 85 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 85 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.ScriptRequest.ResponseId));
            
            #line default
            #line hidden
            this.Write(">(\r\n                woTarget, Request);\r\n        }\r\n");
            
            #line 88 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
 }
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 90 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
 if (modelo.ScriptRequest.UsaDeleteEnRequest){ 
            
            #line default
            #line hidden
            this.Write("        public static ");
            
            #line 91 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(locResponse));
            
            #line default
            #line hidden
            this.Write(" Delete(WoTargetConnection woTarget, ");
            
            #line 91 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(" Request)\r\n        {\r\n            ");
            
            #line 93 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Script Script = new ");
            
            #line 93 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Script();\r\n\r\n            return Script.");
            
            #line 95 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write("Delete<");
            
            #line 95 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.Id));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 95 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelo.ScriptRequest.ResponseId));
            
            #line default
            #line hidden
            this.Write(">(\r\n                woTarget, Request);\r\n        }\r\n");
            
            #line 98 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"
   }
   }
            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 102 "C:\Frog\Blazor\WooW.SB.Config\Templates\ttModeloServicioRequest.tt"

public Modelo modelo { get; set; }  
public string responseObject { get; set; }  
public string locResponse { get; set; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class ttModeloServicioRequestBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
