//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WooW.SB.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WooW.SB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Categories_Add {
            get {
                object obj = ResourceManager.GetObject("Categories-Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Class {
            get {
                object obj = ResourceManager.GetObject("Class", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Class_Friend {
            get {
                object obj = ResourceManager.GetObject("Class-Friend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Code_Snippet_Delete {
            get {
                object obj = ResourceManager.GetObject("Code-Snippet-Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Code_Snippet_Delete1 {
            get {
                object obj = ResourceManager.GetObject("Code-Snippet-Delete1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Code_Snippet_Details {
            get {
                object obj = ResourceManager.GetObject("Code-Snippet-Details", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Code_Snippet_Edit {
            get {
                object obj = ResourceManager.GetObject("Code-Snippet-Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Code_Snippet_Save {
            get {
                object obj = ResourceManager.GetObject("Code-Snippet-Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Code_Snippet_Tick {
            get {
                object obj = ResourceManager.GetObject("Code-Snippet-Tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Columns_1 {
            get {
                object obj = ResourceManager.GetObject("Columns-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Com_Add_Ins {
            get {
                object obj = ResourceManager.GetObject("Com-Add-Ins", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Comment {
            get {
                object obj = ResourceManager.GetObject("Comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Database_Add {
            get {
                object obj = ResourceManager.GetObject("Database-Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Database_Delete {
            get {
                object obj = ResourceManager.GetObject("Database-Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Database_Run {
            get {
                object obj = ResourceManager.GetObject("Database-Run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dbLookup {
            get {
                object obj = ResourceManager.GetObject("dbLookup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dbTable_Add {
            get {
                object obj = ResourceManager.GetObject("dbTable-Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dbTable_Delete {
            get {
                object obj = ResourceManager.GetObject("dbTable-Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dbTable_Delete1 {
            get {
                object obj = ResourceManager.GetObject("dbTable-Delete1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dbTable_Edit {
            get {
                object obj = ResourceManager.GetObject("dbTable-Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dbTable_Import {
            get {
                object obj = ResourceManager.GetObject("dbTable-Import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dbTable_Permission {
            get {
                object obj = ResourceManager.GetObject("dbTable-Permission", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dbTable_Refresh {
            get {
                object obj = ResourceManager.GetObject("dbTable-Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dbTable_Relationships {
            get {
                object obj = ResourceManager.GetObject("dbTable-Relationships", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dbTable_Save {
            get {
                object obj = ResourceManager.GetObject("dbTable-Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Debug_Step_Over {
            get {
                object obj = ResourceManager.GetObject("Debug-Step-Over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Design {
            get {
                object obj = ResourceManager.GetObject("Design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dev_Build {
            get {
                object obj = ResourceManager.GetObject("Dev-Build", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dev_Build_Selection {
            get {
                object obj = ResourceManager.GetObject("Dev-Build-Selection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dev_Build_Selection_16_x_16 {
            get {
                object obj = ResourceManager.GetObject("Dev-Build-Selection 16 x 16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dev_Project_Console {
            get {
                object obj = ResourceManager.GetObject("Dev-Project-Console", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dev_Project_New {
            get {
                object obj = ResourceManager.GetObject("Dev-Project-New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dev_Project_Open {
            get {
                object obj = ResourceManager.GetObject("Dev-Project-Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dev_Project_Open1 {
            get {
                object obj = ResourceManager.GetObject("Dev-Project-Open1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dev_Project_Options {
            get {
                object obj = ResourceManager.GetObject("Dev-Project-Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dev_Project_Save {
            get {
                object obj = ResourceManager.GetObject("Dev-Project-Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Document_C_Sharp {
            get {
                object obj = ResourceManager.GetObject("Document-C-Sharp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Expenses_Error {
            get {
                object obj = ResourceManager.GetObject("Expenses-Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Factory_Details {
            get {
                object obj = ResourceManager.GetObject("Factory-Details", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flow_Chart {
            get {
                object obj = ResourceManager.GetObject("Flow-Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Footnote_Next {
            get {
                object obj = ResourceManager.GetObject("Footnote-Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap History {
            get {
                object obj = ResourceManager.GetObject("History", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_etiquetas_22 {
            get {
                object obj = ResourceManager.GetObject("icons8-etiquetas-22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_etiquetas_32__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-etiquetas-32 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Indent_Decrease {
            get {
                object obj = ResourceManager.GetObject("Indent-Decrease", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Indent_Increase {
            get {
                object obj = ResourceManager.GetObject("Indent-Increase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///    &quot;Estados&quot;: [{
        ///            &quot;Id&quot;: &quot;Nulo&quot;,
        ///            &quot;NumId&quot;: 0,
        ///            &quot;EtiquetaId&quot;: &quot;Nulo&quot;,
        ///            &quot;Tipo&quot;: 0,
        ///            &quot;SubTipo&quot;: 0,
        ///            &quot;Idgrafico&quot;: &quot;69c3d485-3214-48d0-adf7-ed714e9d9292&quot;,
        ///            &quot;Ordenada&quot;: 150.0,
        ///            &quot;Abscisa&quot;: 100.0
        ///        }, {
        ///            &quot;Id&quot;: &quot;Activo&quot;,
        ///            &quot;NumId&quot;: 100,
        ///            &quot;EtiquetaId&quot;: &quot;Activo&quot;,
        ///            &quot;Tipo&quot;: 1,
        ///            &quot;SubTipo&quot;: 0,
        ///            &quot;Idgrafico&quot;: &quot;6695305e-89c5-4375-91c4-e0b109c266de&quot;,
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string JsonCatalogo {
            get {
                return ResourceManager.GetString("JsonCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///    &quot;Items&quot;: [{
        ///            &quot;Numero&quot;: 0,
        ///            &quot;Nombre&quot;: &quot;Manual&quot;,
        ///            &quot;EtiquetaId&quot;: &quot;TransaccionManual&quot;
        ///        }, {
        ///            &quot;Numero&quot;: 1,
        ///            &quot;Nombre&quot;: &quot;Automatica&quot;,
        ///            &quot;EtiquetaId&quot;: &quot;TransaccionAutomatica&quot;
        ///        }, {
        ///            &quot;Numero&quot;: 2,
        ///            &quot;Nombre&quot;: &quot;Movil&quot;,
        ///            &quot;EtiquetaId&quot;: &quot;TransaccionMovil&quot;
        ///        }, {
        ///            &quot;Numero&quot;: 3,
        ///            &quot;Nombre&quot;: &quot;ConsumoServicio&quot;,
        ///            &quot;EtiquetaId&quot;: &quot;TransaccionPorConsumoDeServicio [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string JsonColumnaOrigen {
            get {
                return ResourceManager.GetString("JsonColumnaOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///&quot;Alto&quot;: 0,
        ///&quot;Ancho&quot;: 0,
        ///&quot;Estados&quot;:
        ///    [
        ///        {
        ///        &quot;Abscisa&quot;: 100.0,
        ///        &quot;EtiquetaId&quot;: &quot;Nulo&quot;,
        ///        &quot;Id&quot;: &quot;Nulo&quot;,
        ///        &quot;Idgrafico&quot;: &quot;69c3d485-3214-48d0-adf7-ed714e9d9292&quot;,
        ///        &quot;NumId&quot;: 0,
        ///        &quot;Ordenada&quot;: 150.0,
        ///        &quot;SubTipo&quot;: 0,
        ///        &quot;Tipo&quot;: 0
        ///        },
        ///        {
        ///        &quot;Abscisa&quot;: 400.0,
        ///        &quot;EtiquetaId&quot;: &quot;Activo&quot;,
        ///        &quot;Id&quot;: &quot;Activo&quot;,
        ///        &quot;Idgrafico&quot;: &quot;6695305e-89c5-4375-91c4-e0b109c266de&quot;,
        ///        &quot;NumId&quot;: 100,
        ///        &quot;Ordenada&quot;: 150.0,        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string JsonConfiguracion {
            get {
                return ResourceManager.GetString("JsonConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///    &quot;Estados&quot;: [{
        ///            &quot;Id&quot;: &quot;Nulo&quot;,
        ///            &quot;NumId&quot;: 0,
        ///            &quot;EtiquetaId&quot;: &quot;Nulo&quot;,
        ///            &quot;Tipo&quot;: 0,
        ///            &quot;SubTipo&quot;: 0,
        ///            &quot;Idgrafico&quot;: &quot;69c3d485-3214-48d0-adf7-ed714e9d9292&quot;,
        ///            &quot;Ordenada&quot;: 150.0,
        ///            &quot;Abscisa&quot;: 100.0
        ///        }, {
        ///            &quot;Id&quot;: &quot;Activo&quot;,
        ///            &quot;NumId&quot;: 100,
        ///            &quot;EtiquetaId&quot;: &quot;Activo&quot;,
        ///            &quot;Tipo&quot;: 1,
        ///            &quot;SubTipo&quot;: 0,
        ///            &quot;Idgrafico&quot;: &quot;6695305e-89c5-4375-91c4-e0b109c266de&quot;,
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string JsonControl {
            get {
                return ResourceManager.GetString("JsonControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///    &quot;Alto&quot;: 0,
        ///    &quot;Ancho&quot;: 0,
        ///    &quot;Estados&quot;: [
        ///        {
        ///            &quot;Abscisa&quot;: 100.0,
        ///            &quot;EtiquetaId&quot;: &quot;Nulo&quot;,
        ///            &quot;Id&quot;: &quot;Nulo&quot;,
        ///            &quot;Idgrafico&quot;: &quot;69c3d485-3214-48d0-adf7-ed714e9d9292&quot;,
        ///            &quot;NumId&quot;: 0,
        ///            &quot;Ordenada&quot;: 150.0,
        ///            &quot;SubTipo&quot;: 0,
        ///            &quot;Tipo&quot;: 0
        ///        },
        ///        {
        ///            &quot;Abscisa&quot;: 400.0,
        ///            &quot;EtiquetaId&quot;: &quot;Activo&quot;,
        ///            &quot;Id&quot;: &quot;Activo&quot;,
        ///            &quot;Idgrafico&quot;: &quot;6695305e-89c5-4375-91c4-e0b109c266d [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string JsonKardex {
            get {
                return ResourceManager.GetString("JsonKardex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string JsonNoAplica {
            get {
                return ResourceManager.GetString("JsonNoAplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///&quot;Alto&quot;: 0,
        ///&quot;Ancho&quot;: 0,
        ///&quot;Estados&quot;:
        ///    [
        ///        {
        ///        &quot;Abscisa&quot;: 100.0,
        ///        &quot;EtiquetaId&quot;: &quot;Nulo&quot;,
        ///        &quot;Id&quot;: &quot;Nulo&quot;,
        ///        &quot;Idgrafico&quot;: &quot;69c3d485-3214-48d0-adf7-ed714e9d9292&quot;,
        ///        &quot;NumId&quot;: 0,
        ///        &quot;Ordenada&quot;: 150.0,
        ///        &quot;SubTipo&quot;: 0,
        ///        &quot;Tipo&quot;: 0
        ///        },
        ///        {
        ///        &quot;Abscisa&quot;: 400.0,
        ///        &quot;EtiquetaId&quot;: &quot;Activo&quot;,
        ///        &quot;Id&quot;: &quot;Activo&quot;,
        ///        &quot;Idgrafico&quot;: &quot;6695305e-89c5-4375-91c4-e0b109c266de&quot;,
        ///        &quot;NumId&quot;: 100,
        ///        &quot;Ordenada&quot;: 150.0,        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string JsonParametro {
            get {
                return ResourceManager.GetString("JsonParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///    &quot;Alto&quot;: 0,
        ///    &quot;Ancho&quot;: 0,
        ///    &quot;Estados&quot;: [
        ///        {
        ///            &quot;Abscisa&quot;: 100.0,
        ///            &quot;EtiquetaId&quot;: &quot;Nulo&quot;,
        ///            &quot;Id&quot;: &quot;Nulo&quot;,
        ///            &quot;Idgrafico&quot;: &quot;69c3d485-3214-48d0-adf7-ed714e9d9292&quot;,
        ///            &quot;NumId&quot;: 0,
        ///            &quot;Ordenada&quot;: 150.0,
        ///            &quot;SubTipo&quot;: 0,
        ///            &quot;Tipo&quot;: 0
        ///        },
        ///        {
        ///            &quot;Abscisa&quot;: 400.0,
        ///            &quot;EtiquetaId&quot;: &quot;Activo&quot;,
        ///            &quot;Id&quot;: &quot;Pendiente&quot;,
        ///            &quot;Idgrafico&quot;: &quot;6695305e-89c5-4375-91c4-e0b109c2 [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string JsonTransaccion {
            get {
                return ResourceManager.GetString("JsonTransaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///    &quot;Alto&quot;: 0,
        ///    &quot;Ancho&quot;: 0,
        ///    &quot;Estados&quot;: [
        ///        {
        ///            &quot;Abscisa&quot;: 100.0,
        ///            &quot;EtiquetaId&quot;: &quot;Nulo&quot;,
        ///            &quot;Id&quot;: &quot;Nulo&quot;,
        ///            &quot;Idgrafico&quot;: &quot;69c3d485-3214-48d0-adf7-ed714e9d9292&quot;,
        ///            &quot;NumId&quot;: 0,
        ///            &quot;Ordenada&quot;: 150.0,
        ///            &quot;SubTipo&quot;: 0,
        ///            &quot;Tipo&quot;: 0
        ///        },
        ///        {
        ///            &quot;Abscisa&quot;: 400.0,
        ///            &quot;EtiquetaId&quot;: &quot;Activo&quot;,
        ///            &quot;Id&quot;: &quot;Pendiente&quot;,
        ///            &quot;Idgrafico&quot;: &quot;6695305e-89c5-4375-91c4-e0b109c2 [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string JsonTransaccionContable {
            get {
                return ResourceManager.GetString("JsonTransaccionContable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Label {
            get {
                object obj = ResourceManager.GetObject("Label", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Label_Error {
            get {
                object obj = ResourceManager.GetObject("Label-Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Layout_To_Do_Bar {
            get {
                object obj = ResourceManager.GetObject("Layout-To-Do-Bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap letra_w {
            get {
                object obj = ResourceManager.GetObject("letra-w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap letra_w1 {
            get {
                object obj = ResourceManager.GetObject("letra-w1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap letter {
            get {
                object obj = ResourceManager.GetObject("letter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap News_View {
            get {
                object obj = ResourceManager.GetObject("News-View", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Project_Task_Add {
            get {
                object obj = ResourceManager.GetObject("Project-Task-Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Project_Task_Complete_To_Status_Date {
            get {
                object obj = ResourceManager.GetObject("Project-Task-Complete-To-Status-Date", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Project_Task_Delete {
            get {
                object obj = ResourceManager.GetObject("Project-Task-Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Project_Task_Incomplete_To_Status_Date {
            get {
                object obj = ResourceManager.GetObject("Project-Task-Incomplete-To-Status-Date", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Project_Task_Remove {
            get {
                object obj = ResourceManager.GetObject("Project-Task-Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Query_Design {
            get {
                object obj = ResourceManager.GetObject("Query-Design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Query_Run {
            get {
                object obj = ResourceManager.GetObject("Query-Run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Refresh_All {
            get {
                object obj = ResourceManager.GetObject("Refresh-All", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Repeat {
            get {
                object obj = ResourceManager.GetObject("Repeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Report_Design {
            get {
                object obj = ResourceManager.GetObject("Report-Design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Script {
            get {
                object obj = ResourceManager.GetObject("Script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Script_Edit {
            get {
                object obj = ResourceManager.GetObject("Script-Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Service_Run {
            get {
                object obj = ResourceManager.GetObject("Service-Run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Service_Run_16_x_16 {
            get {
                object obj = ResourceManager.GetObject("Service-Run 16 x 16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Site_Map {
            get {
                object obj = ResourceManager.GetObject("Site-Map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Task_Schedule {
            get {
                object obj = ResourceManager.GetObject("Task-Schedule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Users {
            get {
                object obj = ResourceManager.GetObject("Users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Users_Permission {
            get {
                object obj = ResourceManager.GetObject("Users-Permission", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Window_Code {
            get {
                object obj = ResourceManager.GetObject("Window-Code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Zoom_In_More {
            get {
                object obj = ResourceManager.GetObject("Zoom-In-More", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Zoom_Out {
            get {
                object obj = ResourceManager.GetObject("Zoom-Out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
