// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del runtime: 17.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WooW.SB.BlazorGenerator.BlazorTemplates.CommonTemplates.ControlModels
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Frog\WooW.SB\WooW.SB\BlazorGenerator\BlazorTemplates\CommonTemplates\ControlModels\WoTemplateLoginControlsBlazor.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class WoTemplateLoginControlsBlazor : WoTemplateLoginControlsBlazorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"///------------------------------------------------------------------------------------------------------------------
/// Código autogenerado por la template WoTemplateGenericClass en el path WooW.SB\WooW.SB\BlazorGenerator\BlazorTemplates\CommonTemplates\ControlModels\WoTemplateLoginControlsBlazor.tt
/// Genera código consistente con la version de la prueba de concepto a dia 05-10-2023 En Blazor Wasm y Server
/// Este código es auto generado y su modificación puede causar que el código no se comporte como deveria ademas de
/// que se perderan los cambios realizados en el código al momento de la generación.
///------------------------------------------------------------------------------------------------------------------

using WooW.Blazor;

namespace ");
            
            #line 12 "C:\Frog\WooW.SB\WooW.SB\BlazorGenerator\BlazorTemplates\CommonTemplates\ControlModels\WoTemplateLoginControlsBlazor.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Project));
            
            #line default
            #line hidden
            this.Write(".ControlModels\r\n{\r\n    public class WoLoginControls\r\n    {\r\n        #region Inyec" +
                    "ción de dependencias\r\n\r\n        /// <summary>\r\n        /// Constructor de la cla" +
                    "se con ls instancias que se inyectaran desde el\r\n        /// despachador de depe" +
                    "ndencias de blazor\r\n        /// </summary>\r\n        public WoLoginControls() { }" +
                    "\r\n\r\n        #endregion Inyección de dependencias\r\n\r\n\r\n        /// Layouts y cont" +
                    "enedores\r\n\r\n        #region Root\r\n\r\n        /// <summary>\r\n        /// Instancia" +
                    " de la vista del formulario Root.\r\n        /// </summary>\r\n        public WoForm" +
                    "View Root { get; set; } = new WoFormView();\r\n\r\n        #endregion Root\r\n\r\n      " +
                    "  #region formModelForm\r\n\r\n        /// <summary>\r\n        /// Instancia de la vi" +
                    "sta del input de texto formModelForm.\r\n        /// </summary>\r\n        public Wo" +
                    "FormGroupView formModelForm { get; set; } = new WoFormGroupView();\r\n\r\n        #e" +
                    "ndregion formModelForm\r\n\r\n\r\n        /// Alertas\r\n\r\n        #region Alertas\r\n\r\n  " +
                    "      /// <summary>\r\n        /// Instancia de la vista de las alertas.\r\n        " +
                    "/// </summary>\r\n        public WoFormAlertView Alertas = new WoFormAlertView();\r" +
                    "\n\r\n        #endregion Alertas\r\n\r\n\r\n        #region Usuario\r\n\r\n        /// <summa" +
                    "ry>\r\n        /// Instancia de la vista del input de texto Usuario.\r\n        /// " +
                    "</summary>\r\n        public WoEditView User { get; set; } = new WoEditView();\r\n\r\n" +
                    "        /// <summary>\r\n        /// Instancia de la vista del container de input." +
                    "\r\n        /// </summary>\r\n        public WoFormItemView UserContainer { get; set" +
                    "; } = new WoFormItemView();\r\n\r\n        /// <summary>\r\n        /// Instancia de l" +
                    "as alertas del input.\r\n        /// </summary>\r\n        public WoInputAlertView U" +
                    "serAlert { get; set; } = new WoInputAlertView();\r\n\r\n        #endregion Usuario\r\n" +
                    "\r\n        #region Password\r\n\r\n        /// <summary>\r\n        /// Instancia de la" +
                    " vista del input de texto Password.\r\n        /// </summary>\r\n        public WoEd" +
                    "itView Password { get; set; } = new WoEditView();\r\n\r\n        /// <summary>\r\n    " +
                    "    /// Instancia de la vista del container de input.\r\n        /// </summary>\r\n " +
                    "       public WoFormItemView PasswordContainer { get; set; } = new WoFormItemVie" +
                    "w();\r\n\r\n        /// <summary>\r\n        /// Instancia de las alertas del input.\r\n" +
                    "        /// </summary>\r\n        public WoInputAlertView PasswordAlert { get; set" +
                    "; } = new WoInputAlertView();\r\n\r\n        #endregion Password\r\n\r\n\r\n        #regio" +
                    "n Instance\r\n\r\n        /// <summary>\r\n        /// Instancia de la vista del input" +
                    " de texto Instance.\r\n        /// </summary>\r\n        public WoEditView Instance " +
                    "{ get; set; } = new WoEditView();\r\n\r\n        /// <summary>\r\n        /// Instanci" +
                    "a de la vista del container de input.\r\n        /// </summary>\r\n        public Wo" +
                    "FormItemView InstanceContainer { get; set; } = new WoFormItemView();\r\n\r\n        " +
                    "/// <summary>\r\n        /// Instancia de las alertas del input.\r\n        /// </su" +
                    "mmary>\r\n        public WoInputAlertView InstanceAlert { get; set; } = new WoInpu" +
                    "tAlertView();\r\n\r\n        #endregion Instance\r\n\r\n        #region UDN\r\n\r\n        /" +
                    "// <summary>\r\n        /// Instancia de la vista del input de texto UDN.\r\n       " +
                    " /// </summary>\r\n        public WoEditView Udn { get; set; } = new WoEditView();" +
                    "\r\n\r\n        /// <summary>\r\n        /// Instancia de la vista del container de in" +
                    "put.\r\n        /// </summary>\r\n        public WoFormItemView UdnContainer { get; " +
                    "set; } = new WoFormItemView();\r\n\r\n        /// <summary>\r\n        /// Instancia d" +
                    "e las alertas del input.\r\n        /// </summary>\r\n        public WoInputAlertVie" +
                    "w UdnAlert { get; set; } = new WoInputAlertView();\r\n\r\n        #endregion UDN\r\n\r\n" +
                    "        #region Year\r\n\r\n        /// <summary>\r\n        /// Instancia de la vista" +
                    " del input de texto UDN.\r\n        /// </summary>\r\n        public WoEditView Year" +
                    " { get; set; } = new WoEditView();\r\n\r\n        /// <summary>\r\n        /// Instanc" +
                    "ia de la vista del container de input.\r\n        /// </summary>\r\n        public W" +
                    "oFormItemView YearContainer { get; set; } = new WoFormItemView();\r\n\r\n        ///" +
                    " <summary>\r\n        /// Instancia de las alertas del input.\r\n        /// </summa" +
                    "ry>\r\n        public WoInputAlertView YearAlert { get; set; } = new WoInputAlertV" +
                    "iew();\r\n\r\n        #endregion Year\r\n\r\n        #region InstanceType\r\n\r\n        ///" +
                    " <summary>\r\n        /// Instancia de la vista del input de texto UDN.\r\n        /" +
                    "// </summary>\r\n        public WoEditView InstanceType { get; set; } = new WoEdit" +
                    "View();\r\n\r\n        /// <summary>\r\n        /// Instancia de la vista del containe" +
                    "r de input.\r\n        /// </summary>\r\n        public WoFormItemView InstanceTypeC" +
                    "ontainer { get; set; } = new WoFormItemView();\r\n\r\n        /// <summary>\r\n       " +
                    " /// Instancia de las alertas del input.\r\n        /// </summary>\r\n        public" +
                    " WoInputAlertView InstanceTypeAlert { get; set; } = new WoInputAlertView();\r\n\r\n " +
                    "       #endregion InstanceType\r\n\r\n        #region LoginButton\r\n\r\n        /// <su" +
                    "mmary>\r\n        /// Instancia de la vista del botón de logeo\r\n        /// </summ" +
                    "ary>\r\n        public WoButtonView LoginButton { get; set; } = new WoButtonView()" +
                    ";\r\n\r\n        /// <summary>\r\n        /// Instancia de la vista del container de i" +
                    "nput.\r\n        /// </summary>\r\n        public WoFormItemView LoginContainer { ge" +
                    "t; set; } = new WoFormItemView();\r\n\r\n        #endregion LoginButton\r\n    }\r\n}\r\n\r" +
                    "\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 191 "C:\Frog\WooW.SB\WooW.SB\BlazorGenerator\BlazorTemplates\CommonTemplates\ControlModels\WoTemplateLoginControlsBlazor.tt"

public string Project { get; set; } = "";

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class WoTemplateLoginControlsBlazorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
